mode: test
lmdb: false
dataset_root_rgb: "/data/dataset/intellectus"
lmdb_dir: I:\transform_2_lmdb
dataset_json_folder: /data/users/dahye/workspace/iclr/baseline/effort/Effort-AIGI-Detection/DeepfakeBench/preprocessing/dataset_json
label_dict:
  Midjourney_Real: 0
  Midjourney_Fake: 1
  amused_Real: 0
  amused_Fake: 1
  flux_Real: 0
  flux_Fake: 1
  kandinsky_Real: 0
  kandinsky_Fake: 1
  lcm_Real: 0
  lcm_Fake: 1
  pixelart_Real: 0
  pixelart_Fake: 1
  playground_Real: 0
  playground_Fake: 1
  sd_Real: 0
  sd_Fake: 1
  wuerstchen_Real: 0
  wuerstchen_Fake: 1
  HiDF_Real: 0
  HiDF_Fake: 1
